app:
  name: "Sample Application"
  version: "1.0.0"
  debug: false

database:
  host: "localhost"
  port: 5432
  name: "sample_db"

api:
  host: "0.0.0.0"
  port: 8000
  timeout: 30

logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
